### ISSUE TITLE
Need to create more detail doc for this project

### ISSUE THREAD

**Issue by shivrajsa** [surikov/SSSynthesiser.js#3]
It is necessary to create more detail doc about how to implement this project, it will help .
1. Please add info about how to edit Malgov file for instruments which are not available in malgov.
2. How to create "signed" array for such instruments.
3. What does parameters of function means "playKey(sssynthesiser.findSampleBySubPath(s),1000,45);"
4. Overall information about structure of Malgov file
5. how many properties available with instrument "sssynthesiser.findSampleBySubPath("drums/000/Chaos_128/061_046-046_60_-4600.0_8-34789_32000").volume = 0.25;"

**Comment by surikov** [comment]
see this http://habrahabr.ru/post/266145/
