### ISSUE TITLE
How to loop playKey or playChord function 

### ISSUE THREAD

**Issue by shivrajsa** [surikov/SSSynthesiser.js#5]
In my project I have used MIDI.js & basically I am checking this library if this can be replacement to MIDI.js. Because if I understood correctly this library has good support on mobile too and it works locally without internet.
I am comparing functions of this library with MIDI.js functions to check its compatibility in my project.

I tried to loop a note in for loop, but it does not work, it plays only once. How to do that.

```
function hitKey(n){
        if (ready()) {
        for(var i=0;i<10;i++)
            {
                    sssynthesiser.playKey(sssynthesiser.findSampleBySubPath("instruments/000/Chaos_000/003_048-052_60_-5000_8-32231_22050"),3000+i*10,n);
            }
        }
    }
```

**Comment by surikov** [comment]
- load song
- add new riff to the song
- remove all positions from the song
- add new position with the riff
- add one note to the riff
