### ISSUE TITLE
How to integrate local 'molgav' file?

### ISSUE THREAD

**Issue by shivrajsa** [surikov/SSSynthesiser.js#6]
In your example molgav file is used from 

```
xmlHttpRequest.open('GET', "http://molgav.nn.ru/x/sviridovtimeforward.molgav", true);

"path" : "http://molgav.nn.ru/sf/drums/000/Chaos_128/061_046-046_60_-4600.0_8-34789_32000",
```

How can I use local molgav file?

**Comment by surikov** [comment]
JS
function loadFile(event) {
  var fileReader = new FileReader();
  fileReader.onload = function (progressEvent) {
    console.log(progressEvent.target.result);
    };
  fileReader.readAsText(event.target.files[0]);
}

html
<input type="file" onchange="loadFile(event)"/>
